name: Node.js Package (Backend + Frontend + Web Preview)

on:
  release:
    types: [created]

jobs:
  # =======================================
  # FRONTEND TESTS + WEB BUILD PREVIEW
  # =======================================
  frontend-tests:
    name: Build and Test Frontend (Expo Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test || echo "No frontend tests yet 🚧"

      - name: Build Expo web app
        run: npx expo export --platform web

      - name: Upload web preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-web-preview
          path: dist
          retention-days: 5

  # =======================================
  # BACKEND TESTS
  # =======================================
  backend-tests:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kivelo-backend
    needs: frontend-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: kivelo-backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test

  # =======================================
  # PUBLISH TO GITHUB PACKAGES
  # =======================================
  publish-gpr:
    name: Publish to GitHub Packages
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: kivelo-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
